#!/usr/bin/env python3
"""Refresh the profile's upstream activity list and date-seeded footer.

Generic GitHub statistics and language cards are generated by the mature
`stats-organization/github-readme-stats-action` workflow. This script only
owns the profile-specific upstream PR list and footer rotation.
"""
from __future__ import annotations

import datetime as dt
import html
import json
import os
import shutil
import subprocess
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
DATA = ROOT / "data" / "content.json"
LIVE = ROOT / "data" / "live.json"
LOGIN = os.environ.get("PROFILE_LOGIN", "teddyli18000")
TOKEN = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
SGT = dt.timezone(dt.timedelta(hours=8), name="SGT")


def api(path: str) -> dict:
    request = urllib.request.Request(f"https://api.github.com/{path}")
    request.add_header("Accept", "application/vnd.github+json")
    request.add_header("User-Agent", f"{LOGIN}-profile-readme")
    request.add_header("X-GitHub-Api-Version", "2022-11-28")
    if TOKEN:
        request.add_header("Authorization", f"Bearer {TOKEN}")
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)
    except Exception:
        if not shutil.which("gh"):
            raise
        proc = subprocess.run(["gh", "api", path], capture_output=True, check=True)
        return json.loads(proc.stdout)


def fetch_external() -> list[dict]:
    query_string = urllib.parse.urlencode({"q": f"author:{LOGIN} type:pr -user:{LOGIN}", "per_page": 50})
    pulls = api(f"search/issues?{query_string}")
    external: list[dict] = []
    for item in pulls["items"]:
        repo = item["repository_url"].split("/repos/", 1)[1]
        number = item["number"]
        detail = api(f"repos/{repo}/pulls/{number}")
        status = "merged" if detail.get("merged") else ("draft" if detail.get("draft") else item["state"])
        external.append(
            {
                "repo": repo,
                "number": number,
                "title": item["title"],
                "url": item["html_url"],
                "status": status,
                "updated_at": item["updated_at"],
            }
        )
    return external


def choose_external(items: list[dict]) -> list[dict]:
    rank = {"merged": 0, "open": 1, "draft": 2, "closed": 3}
    return sorted(
        items,
        key=lambda item: (
            rank.get(item["status"], 4),
            -dt.datetime.fromisoformat(item["updated_at"].replace("Z", "+00:00")).timestamp(),
        ),
    )[:3]


def signature(items: list[dict]) -> list[dict]:
    return [
        {key: item[key] for key in ("repo", "number", "title", "url", "status")}
        for item in items
    ]


def last_good() -> tuple[list[dict], list[dict], dt.datetime]:
    snapshot = json.loads(LIVE.read_text(encoding="utf-8"))
    external = snapshot.get("external") or []
    selected = snapshot.get("selected_external") or choose_external(external)
    if len(selected) != 3:
        raise ValueError("live.json does not contain three last-good upstream PRs")
    stamp_raw = snapshot.get("updated_at")
    if not stamp_raw:
        raise ValueError("live.json is missing updated_at")
    stamp = dt.datetime.fromisoformat(stamp_raw.replace("Z", "+00:00")).astimezone(SGT)
    return external, selected, stamp


def collect() -> tuple[list[dict], list[dict], dt.datetime, bool, bool]:
    try:
        external = fetch_external()
        selected = choose_external(external)
        if len(selected) != 3:
            raise ValueError(f"expected three upstream pull requests, got {len(selected)}")
        now = dt.datetime.now(SGT)
        try:
            _, previous_selected, previous_stamp = last_good()
            changed = signature(selected) != signature(previous_selected)
            updated = now if changed else previous_stamp
        except Exception:
            changed = True
            updated = now
        return external, selected, updated, True, changed
    except Exception as error:
        external, selected, stamp = last_good()
        print(f"GitHub refresh failed ({error}); retaining last-good data from {stamp.isoformat()}")
        return external, selected, stamp, False, False


def replace_block(text: str, name: str, body: str) -> str:
    start = f"<!-- profile-{name}:start -->"
    end = f"<!-- profile-{name}:end -->"
    if text.count(start) != 1 or text.count(end) != 1:
        raise ValueError(f"expected exactly one {start} and {end}")
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    return f"{before}{start}\n{body.rstrip()}\n{end}{after}"


def live_markdown(selected: list[dict]) -> str:
    notes = json.loads(DATA.read_text(encoding="utf-8")).get("external_notes", {})
    lines = [
        '<p align="center">',
        '  <img width="49%" src="./assets/stats-card.svg" alt="GitHub activity statistics.">',
        '  <img width="49%" src="./assets/languages-card.svg" alt="Most used languages across public GitHub repositories.">',
        '</p>',
        '',
        '**Outside my repos**',
        '',
    ]
    for item in selected:
        key = f"{item['repo']}#{item['number']}"
        note = notes.get(key, item["title"])
        marker = "✓ merged" if item["status"] == "merged" else f"↗ {item['status']}"
        lines.append(f"- {marker} → [{item['repo']} #{item['number']}]({item['url']}) · {note}")
    return "\n".join(lines)


def footer_markdown(today: dt.datetime) -> str:
    content = json.loads(DATA.read_text(encoding="utf-8"))
    pool = content["footer_lines"]
    item = pool[int(today.strftime("%Y%j")) % len(pool)]
    text = html.escape(item["text"])
    author = item.get("author")
    suffix = f" — {html.escape(author)}" if author else ""
    return f'<sub><em>“{text}”</em>{suffix}</sub>'


def main() -> None:
    external, selected, updated, fresh, changed = collect()
    text = README.read_text(encoding="utf-8")
    text = replace_block(text, "live", live_markdown(selected))
    text = replace_block(text, "footer", footer_markdown(dt.datetime.now(SGT)))
    README.write_text(text, encoding="utf-8", newline="\n")

    if fresh and changed:
        snapshot = {
            "external": external,
            "selected_external": selected,
            "updated_at": updated.isoformat(),
        }
        LIVE.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    state = "Updated" if changed else ("Checked" if fresh else "Retained")
    print(f"{state} {len(external)} upstream PRs; showing {len(selected)} at {updated.isoformat()}")


if __name__ == "__main__":
    main()
